MAX_PROJECT_NAME_LENGTH = 100
MIN_FULL_AMOUNT_VALUE = 1
MIN_FIELD_LENGTH = 2
DEFAULT_INVESTED_AMOUNT_VALUE = 0
PASSWORD_MIN_LENGTH = 3
MAX_ROW_COUNT = 100
MAX_COLUMN_COUNT = 4
FORMAT = "%Y/%m/%d %H:%M:%S"