MAX_PROJECT_NAME_LENGTH = 100
MIN_FULL_AMOUNT_VALUE = 1
MIN_FIELD_LENGTH = 2
DEFAULT_INVESTED_AMOUNT_VALUE = 0
PASSWORD_MIN_LENGTH = 3
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
FORMAT = "%Y/%m/%d %H:%M:%S"